server:
  port: ${PORT:8080}

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: buscador
          uri: lb://buscador
          predicates:
            - Path=/items/**
        - id: operador
          uri: lb://operador
          predicates:
            - Path=/compras/**
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "https://tienda-online-react-unir-uriel-mart.vercel.app"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-58gd.onrender.com/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
