server:
  port: 8080

spring:
  application:
    name: cloud-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: operador
              uri: lb://operador
              predicates:
                - Path=/compras/**
            - id: buscador
              uri: lb://buscador
              predicates:
                - Path=/items/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,env
  endpoint:
    gateway:
      access: read-only